<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div>
    <div class="order-history">
        <table class="admin__table-secondary order-account-information-table">
            <tbody>
                <tr>
                    <th><?= __('Customer Code') ?></th>
                    <td><?= $block->getClient()->getCustomerCode() ?></td>
                </tr>
                <tr>
                    <th><?= __('Customer Name') ?></th>
                    <td><?= $block->getClient()->getCustomerName() ?></td>
                </tr>
                <tr>
                    <th><?= __('Address Code') ?></th>
                    <td><?= $block->getAddress()->getAddressCode() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="order-totals">
        <table class="admin__table-secondary order-account-information-table">
            <tbody>
                <tr>
                    <th><?= __('Street') ?></th>
                    <td><?= $block->getAddress()->getData("address1") ?><br /><?= $block->getAddress()->getData("address2") ?></td>
                </tr>
                <tr>
                    <th><?= __('City') ?></th>
                    <td><?= $block->getAddress()->getCity() ?></td>
                </tr>
                <tr>
                    <th><?= __('State') ?></th>
                    <td><?= $block->getAddress()->getState() ?></td>
                </tr>
                <tr>
                    <th><?= __('Country') ?></th>
                    <td><?= $block->getAddress()->getCountry() ?></td>
                </tr>
                <tr>
                    <th><?= __('Phone') ?></th>
                    <td><?= $block->getAddress()->getPhone() ?></td>
                </tr>
                <tr>
                    <th><?= __('Email') ?></th>
                    <td><?= $block->getAddress()->getEmail() ?></td>
                </tr>
                <tr>
                    <th><?= __('Buyer Name') ?></th>
                    <td><?= $block->getAddress()->getBuyerName() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
