<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div id="select_factory_modal"></div>
<div id="select_address_modal"></div>
<div id="select_items_modal"></div>
<form class="new_asn_form">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= __('Factory') ?></span>
            <button
                class="primary"
                style="float: right"
                id="select_factory_button"
                disabled="disabled"
            >
                <?= __('Select Factory') ?>
            </button>
        </legend>
        <div id="selected_factory">
            <?= __('Not selected') ?>
        </div>
    </fieldset>

    <fieldset class="fieldset">
        <div id="react-category-root"></div>
    </fieldset>
</form>
<script type="text/x-magento-init">
{
    "#select_factory_button" : {
        "asnCreator_selectFactoryButton": {
            "selected_factory_box": "selected_factory",
            "cartons_box": "cartons",
            "url": "<?= $this->getUrl('itvoice_asn_creator/SelectFactory/Index') ?>",
            "modal_id": "select_factory_modal",
            "refresh_factory_box_url": "<?= $this->getUrl('itvoice_asn_creator/index/factory') ?>",
            "factory_get_items_url": "<?= $this->getUrl('itvoice_asn_creator/factory/getitems') ?>"
        }
    }
}
</script>
