<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div id="select_factory_modal"></div>
<div id="add_carton_modal"></div>
<form class="new_asn_form">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= __('Factory') ?></span>
            <button
                class="primary"
                style="float: right"
                id="select_factory_button"
                disabled="disabled"
            >
                <?= __('Select Factory') ?>
            </button>
        </legend>
        <div id="selected_factory">
            <?= __('Not selected') ?>
        </div>
    </fieldset>
    <fieldset class="fieldset" style="display: none" id="cartons">
        <legend class="legend">
            <span><?= __('Cartons') ?></span>
            <button
                class="primary"
                style="float: right"
                id="add_carton_button"
            >
                <?= __('Add Carton') ?>
            </button>
        </legend>
        <div id="carton_list">
            <?= __('None') ?>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    window.selectedFactoryId = null;
    window.selectedAddressId = null;
</script>
<script type="text/x-magento-init">
{
    "#select_factory_button" : {
        "asnCreator_selectFactoryButton": {
            "selected_factory_box": "selected_factory",
            "cartons_box": "cartons",
            "carton_list_box": "carton_list",
            "url": "<?= $this->getUrl('itvoice_asn_creator/SelectFactory/Index') ?>",
            "modal_id": "select_factory_modal",
            "refresh_factory_box_url": "<?= $this->getUrl('itvoice_asn_creator/index/factory') ?>"
        }
    },
    "#add_carton_button" : {
        "asnCreator_addCartonButton": {
            "modal_id": "add_carton_modal",
            "url": "<?= $this->getUrl('itvoice_asn_creator/AddCarton/Index') ?>"
        }
    }
}
</script>
