<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php echo 'ASN ID: ' . $block->getAsn()->getId() ?>
<br/>
<?php echo 'FACTORY ID: ' . $block->getAsn()->getFactory(true)->getId() ?>
<div id="select_factory_modal"></div>
<form class="new_asn_form">
    <fieldset class="fieldset">
        <div id="selected_factory">
            <?= __('Not selected') ?>
        </div>
    </fieldset>

    <fieldset class="fieldset">
        <div id="react-category-root"></div>
    </fieldset>
</form>
<script type="text/x-magento-init">
{
    "#select_factory_button" : {
        "asnCreator_selectFactoryButton": {
            "selected_factory_box": "selected_factory",
            "cartons_box": "cartons",
            "url": "<?= $this->getUrl('itvoice_asn_creator/SelectFactory/Index') ?>",
            "modal_id": "select_factory_modal",
            "refresh_factory_box_url": "<?= $this->getUrl('itvoice_asn_creator/index/factory') ?>",
            "factory_get_items_url": "<?= $this->getUrl('itvoice_asn_creator/factory/getitems') ?>",
            "factory_post_cartons_url": "<?= $this->getUrl('itvoice_asn_creator/index/create') ?>"
        }
    }
}
</script>
