<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php
/** @var \ITvoice\AsnCreator\Block\Adminhtml\Editor\Factory $block */
?>
<?= $block->getCloseButton() ?>
<form class="new_asn_form">
    <fieldset class="fieldset">
        <div id="selected_factory">
            <?= $block->getChildHtml('itvoice.asn.editor.factory') ?>
        </div>
    </fieldset>

    <fieldset class="fieldset">
        <div id="react-category-root"></div>
    </fieldset>
</form>
<script type="text/x-magento-init">
{
    "*" : {
        "asnEditor": {
            "asn_id": "<?= $block->getAsn()->getId() ?>",
            "factory_id": "<?= $block->getAsn()->getFactory(true)->getId() ?>",
            "factory_get_items_url": "<?= $this->getUrl('itvoice_asn_creator/factory/getitems', ['asn_id' => $block->getAsn()->getId()]) ?>",
            "factory_post_cartons_url": "<?= $this->getUrl('itvoice_asn_creator/asn/save', ['asn_id' => $block->getAsn()->getId()]) ?>"
        }
    }
}
</script>
